# Dockerfile-node
FROM node:20.9.0

WORKDIR /app

# Copy package.json and package-lock.json (if availab
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application files
COPY . .

# Expose the necessary port (if your app uses a specific port)
EXPOSE 3000

# Run your application
CMD ["npm", "run", "dev"]
